footprint: [[-0.089, -0.069], [-0.089, 0.069], [0.089, 0.069], [0.089, -0.069]]
footprint_padding: 0.01

robot_base_frame: base_footprint
update_frequency: .5
publish_frequency: .5
transform_tolerance: 5

resolution: 0.02

obstacle_range: 2.5
raytrace_range: 3.0

#layer definitions
static:
    map_topic: map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: lidar, inf_is_valid: true}

inflation:
    inflation_radius: 0.30
