footprint: [[-0.33, -0.33], [-0.33, 0.33], [0.33, 0.33], [0.33, -0.33]]
footprint_padding: 0.01

robot_base_frame: base_footprint
update_frequency: 1
publish_frequency: 1
transform_tolerance: 10

resolution: 0.02

obstacle_range: 7.0
raytrace_range: 7.0

#layer definitions
static:
    map_topic: map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: lidar
    lidar: {data_type: LaserScan, clearing: true, marking: true, topic: lidar, inf_is_valid: true}

inflation:
    inflation_radius: 1.0
