footprint: [[-0.089, -0.069], [-0.089, 0.069], [0.089, 0.069], [0.089, -0.069]]
footprint_padding: 0.01

robot_base_frame: R1/base_link
update_frequency: 3.0
publish_frequency: 3.0
transform_tolerance: 2

resolution: 0.02

obstacle_range: 2.5
raytrace_range: 3.0

#layer definitions
static:
    map_topic: /R1/map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: laser
    laser: {data_type: LaserScan, clearing: true, marking: true, topic: /R1/scan, inf_is_valid: true}

inflation:
    inflation_radius: 0.30
